[module]
  [module.hugoVersion]
    extended = true
    min = "0.146.0"

[params]
  # CanIUse Embed Element Configuration
  # See: https://github.com/Lruihao/caniuse-embed-element
  [params.caniuse_embed]
    # show the past N versions that match the feature, range is 0 - 5, default is 2
    past = 2
    # show the future N versions that match the feature, range is 0 - 3, default is 1
    future = 1
    # the origin of the caniuse embed data source, default is "https://caniuse.lruihao.cn"
    origin = "https://caniuse.lruihao.cn"
    # loading strategy for the iframe (eager or lazy), default is lazy
    loading = "lazy"
    # only production environment effective
    # e.g. https://unpkg.com/@cell-x/caniuse-embed-element/dist/caniuse-embed-element.iife.js
    cdn = ""
